language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

env:
  global:
    - ENCRYPTION_LABEL: "052ccc0f979b"
    - COMMIT_AUTHOR_EMAIL: "ping@users.noreply.github.com"

script:
  - find {src,examples} -name '*.php' -print0 | xargs -0 -n1 -P8 php -l | grep -v '^No syntax errors detected'; test $? -eq 1

after_success:
  # Only run gh-pages build if it's not a PR, is master, and by the php5.6 job
  - if [ "$TRAVIS_PULL_REQUEST" == 'false' ] && [ "$TRAVIS_BRANCH" == 'master' ] && [ "$TRAVIS_PHP_VERSION" == '5.6' ]; then (sudo apt-get install -y graphviz && chmod +x .github/build_ghpages.sh && bash .github/build_ghpages.sh); fi

branches:
  only:
    - master
